"""add_user_role

Revision ID: 17845bf84fa9
Revises: cfd9322fa56b
Create Date: 2025-12-02 14:10:06.045196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17845bf84fa9'
down_revision = 'cfd9322fa56b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), server_default='MEMBER', nullable=False))
    op.execute("UPDATE users SET role = 'MEMBER' WHERE role IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###

